dist: trusty
services:
- docker
- docker-engine
addons:
  apt:
    packages: sshpass
language: bash
before_install:
- openssl aes-256-cbc -K $encrypted_17fe5c8c02ba_key -iv $encrypted_17fe5c8c02ba_iv
  -in conf/application.conf.enc -out conf/application.conf -d
- bash docker_install.sh
- export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH;
  else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
- export YVIDEO_VERSION=$(if [ "$BRANCH" == "master" ]; then echo "--production";
  else echo "--beta"; fi)
- cd ..
- git clone --branch master --depth 1 https://github.com/BYU-ODH/yvideo-deploy
- cp -r yvideo yvideo-deploy/test/yvideo/
- cd yvideo-deploy
- bash setup_yvideo.sh --travis
script:
- cd /home/travis/build/BYU-ODH/yvideo
- bash sbt_test_result.sh
after_success:
- sshpass -p $serverpassword $sshuser@$host /var/yvideo/yvideo-deploy/setup_yvideo.sh
  $YVIDEO_VERSION --build
