dist: trusty
language: bash
before_install:
- openssl aes-256-cbc -K $encrypted_71aebdc98bb4_key -iv $encrypted_71aebdc98bb4_iv -in conf/secrets.tar.enc -out secrets.tar -d
- tar xf secrets.tar
- cp travis.application.conf conf/application.conf
- bash .travis-install-docker.sh
- export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH;
  else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
- cd ..
- git clone --branch master --depth 1 https://github.com/BYU-ODH/yvideo-deploy
- cd yvideo-deploy
- bash setup_yvideo.sh --travis
script:
- cd $TRAVIS_BUILD_DIR
- bash .travis-test-result.sh
deploy:
- provider: script
  skip_cleanup: true
  script: bash .travis-deploy.sh
  on:
    all_branches: true
    condition: "$BRANCH =~ ^master|develop$"
